### ISSUE TITLE
Automation to keep plotters-iced updated with iced

### ISSUE THREAD

**Issue by GyulyVGC** [Joylei/plotters-iced#12]
Hi! Today iced has been updated to 0.7 and this broke the compatibility with plotters-iced.

I was wondering if it'd be possible to automate the update process to keep the dependencies/releases automatically up to date.

Setting up [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) could be a good starting point.

Another possible solution would be to involve @hecrj in someway into this project.

Let me know what do you think guys and if I can be of any help!

**Comment by Joylei** [comment]
Dependabot is good. You can create a PR for it.
If there are breaking changes in Iced,  we have to fix it manually. 
Anyone is welcome to contribute on this project.

**Comment by GyulyVGC** [comment]
I'll create a dependabot PR then!
