### ISSUE TITLE
Can't figure out how to upgrade my project to 0.9

### ISSUE THREAD

**Issue by Davidster** [Joylei/plotters-iced#29]
Hey! Thanks for the great library. It was super helpful for me in getting a nice FPS graph overlay in [ikari](https://github.com/Davidster/ikari).

It's now been many hours that I've tried to upgrade to iced 0.10.0 + plotters-iced 0.9.0 in ikari and I haven't had any luck getting it to work. There seems to be something wrong with the `Renderer` trait but I honestly can't make much sense of the error message. Maybe you'd be able to help. 

I created a [repo](https://github.com/Davidster/plotters-iced-repro-case) that reproduces the issue, just uncomment [line 65 in chart.js](https://github.com/Davidster/plotters-iced-repro-case/blob/82531bbed53c6d93a61c9907fdd117abcb5ad39a/src/chart.rs#L65). It will yield a very cryptic error message:

```rust
error[E0277]: the trait bound `iced_widget::iced_graphics::Renderer<iced_wgpu::Backend, iced::Theme>: plotters_iced::renderer::Renderer` is not satisfied
  --> src\chart.rs:66:26
   |
66 |             Element::new(_chart);
   |             ------------ ^^^^^^ the trait `plotters_iced::renderer::Renderer` is not implemented for `iced_widget::iced_graphics::Renderer<iced_wgpu::Backend, iced::Theme>`
   |             |
   |             required by a bound introduced by this call
   |
   = help: the trait `plotters_iced::renderer::Renderer` is implemented for `iced_widget::iced_renderer::Renderer<Theme>`
   = note: required for `ChartWidget<'_, Message, iced_widget::iced_graphics::Renderer<iced_wgpu::Backend, iced::Theme>, &MyBasicChart>` to implement `iced_widget::iced_core::Widget<Message, iced_widget::iced_graphics::Renderer<iced_wgpu::Backend, iced::Theme>>`
note: required by a bound in `iced_widget::iced_core::Element::<'a, Message, Renderer>::new`
  --> .cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_core-0.10.0\src\element.rs:31:29
   |
31 |     pub fn new(widget: impl Widget<Message, Renderer> + 'a) -> Self
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Element::<'a, Message, Renderer>::new`
```

For sanity, I also created a [branch](https://github.com/Davidster/plotters-iced-repro-case/tree/b406c3f171b5cb8afbd0cb6c253e67e3640dd11d) which downgrades to iced 0.9 + plotters-iced 0.8 and demonstrates the same setup (as close as I could get it) working fine:

![image](https://github.com/Joylei/plotters-iced/assets/2389735/be80999a-91fe-40e9-8004-9b4ccb69e3f5)

I wonder if you'd have any ideas to help debugging this? There's 10000 different versions of the Renderer type and I'm completely lost. My best guess is that it's something to do with adding another implementation of `plotters-rs::renderer::Renderer` in [renderer.rs](https://github.com/Joylei/plotters-iced/blob/33aee2a311ea47bc5da5469bb10cd2c805c9679b/src/renderer.rs). 

Thanks!

**Comment by Davidster** [comment]
@GyulyVGC seeing as how you worked on the upgrade to iced 0.10 I wonder if you'd have any ideas about it? 😄

**Comment by MartensCedric** [comment]
have the same issue :disappointed:

**Comment by GyulyVGC** [comment]
> @GyulyVGC seeing as how you worked on the upgrade to iced 0.10 I wonder if you'd have any ideas about it? 😄 

I think it has to due with the fact that now iced chooses the renderer at runtime.
Have you tried to change the renderer used in the return type of your view function?

**Comment by Joylei** [comment]
agree with @GyulyGVC. Iced changes a lot，please check examples in the library.

**Comment by Davidster** [comment]
Yes I tried messing with the type of Renderer and wasn't able to make it work. The one that is specified in my view function is the one that is needed by my iced program due to the way I'm using the library (instead of implementing Sandbox or Application, I'm implementing Program). 

I suspect that plotters-iced needs to support the renderer type specified in my view function for this 'impl Program' style to work.

My repro case is a direct copy of the 'integration' example from iced, I'm not aware of another example that uses the impl Program flow.

Do you have any other ideas?

**Comment by GyulyVGC** [comment]
I tried making your repo work but I failed as well and the reason is exactly the renderer passed as parameter to the Program (https://github.com/Davidster/plotters-iced-repro-case/blob/master/src/main.rs#L141).

I successfully migrated [my repo](https://github.com/GyulyVGC/sniffnet) to iced 0.10 but I'm implementing the Application trait, so I'm not able to help in this case.

Probably something should actually change from `plotters-iced` side.

**Comment by Davidster** [comment]
thanks for checking! okay, I will try to poke around some more in plotters-iced to see if I can get it to compile

**Comment by Joylei** [comment]
`graphics::geometry::Renderer` was implemented for iced_renderer::Renderer, but not for `iced_wgpu::Renderer`. It's impossible to make it work without this.

**Comment by Davidster** [comment]
thanks for confirming. I tried fixing it for a couple more hours but I didn't really get anywhere. I will open an issue with iced

**Comment by matthieugayon** [comment]
FYI, we found a solution [here](https://github.com/matthieugayon/integration-test/tree/master) that might help you out.
Specially [here](https://github.com/matthieugayon/integration-test/blob/c5e1efd5f0014cdc36ed66e3539ba1cf829e0052/src/main.rs#L111)

**Comment by Davidster** [comment]
@matthieugayon thank you! this seems to work. I appreciate the help

**Comment by Davidster** [comment]
I have submitted a pull request on iced so other users won't run into this: https://github.com/iced-rs/iced/pull/2063
