### ISSUE TITLE
Flawed documentation

### ISSUE THREAD

**Issue by qoheniac** [Joylei/plotters-iced#31]
In the documentation for [Chart's draw method](https://docs.rs/plotters-iced/0.9.0/plotters_iced/trait.Chart.html#method.draw) the links are broken and the example isn't working.

**Comment by GyulyVGC** [comment]
I've just opened #32 to fix broken links, but that example is deliberately ignored by CI and don't appear to be complete... it's intended probably just as a hint.

**Comment by qoheniac** [comment]
Thanks. I did not mean that it's incomplete but the argument count of `R::draw` is wrong. Maybe it's supposed to be `R::draw_cache`.

**Comment by GyulyVGC** [comment]
Actually you are right.
Updated the PR.
Thanks!
