### ISSUE TITLE
Outdated Iced Backend

### ISSUE THREAD

**Issue by BeaconBrigade** [Joylei/plotters-iced#4]
When creating a simple gui with a text box and a graph, when setting widths/lengths for both, the program fails to compile saying 

expected enum `iced_core::length::Length`, found enum `Length`. 

It suggests that multiple versions of `iced_core` are being used. I'm using iced version 0.4, which uses iced_native 0.5. I looked, and it seems like this repository is using iced_native 0.4. I think this is preventing people from using newer versions of iced in conjunction with plotters-iced. Is there any possibility this repository will be updated? Or is there another issue here?

**Comment by Joylei** [comment]
I will update it this weekend

**Comment by Joylei** [comment]
code was updated. but there is some problem with web version.

**Comment by BeaconBrigade** [comment]
Hey thanks a lot, I think the build for ubuntu failed because the example `split-chart` has a `Cargo.toml` named `cargo.toml`. The build is looking for one starting with a capital C.

**Comment by Joylei** [comment]
done
