### ISSUE TITLE
iced is now pure by default; iced_pure deprecated

### ISSUE THREAD

**Issue by black-puppydog** [Joylei/plotters-iced#7]
The pure way of doing things seems to be the default now: https://github.com/iced-rs/iced/pull/1393

Note that this change hasn't been released yet, but it's coming so just a heads-up. 🙂

**Comment by Joylei** [comment]
It's already there in the next branch, will be released once iced new version is published.

**Comment by black-puppydog** [comment]
wow I had totally forgotten to check for that. only checked in PRs and issues 🙈 Sorry for the noise, and thanks for the library! 🙂
