### ISSUE TITLE
Should be updated to use `iced` 0.5

### ISSUE THREAD

**Issue by yjhn** [Joylei/plotters-iced#8]
`iced` 0.5 was recently released. This causes (if you try to use `iced` 0.5 in your project) type mismatches with, for example, `iced_core::length::Length` (mismatch between `iced_core` 0.5 and 0.6), thus making it impossible to use `iced` 0.5 with this library.

**Comment by dam5h** [comment]
Looks like it's underway: https://github.com/Joylei/plotters-iced/issues/7

Check out the `next` branch.

**Comment by Joylei** [comment]
The new version was released.
